chain = "mainnet"
datadir = "$DATA_DIR"
sync-mode = "full"
keystore-dir = "$BOR_DIR/keystore"

[accounts]
allow-insecure-unlock = true
password-file = "$BOR_DIR/password.txt"
unlock = ["$ADDRESS"]

[jsonrpc]
ipc-path = "$DATA_DIR/bor.ipc"

[jsonrpc.http]
enabled = true
host = "127.0.0.1"
vhost = ["*"]
cors = ["*"]
port = 8545
api = ["eth", "net", "web3", "txpool", "bor"]

[p2p]
port = 30303
maxpeers = 200

[sealer]
enabled = true
gas-ceil = 20000000
gas-price = 30000000000

[telemetry]
enabled = true

[txpool]
account-queue = 16
account-slots = 16
global-queue = 32768
global-slots = 32768
lifetime = "1h30m0s"
no-locals = true
price-limit = 30000000000
